package com.atguigu.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CasePaid implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.case_id
     *
     * @mbggenerated
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.ptp_time
     *
     * @mbggenerated
     */
    private Date ptpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.ptp_money
     *
     * @mbggenerated
     */
    private BigDecimal ptpMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cp_time
     *
     * @mbggenerated
     */
    private Date cpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cp_money
     *
     * @mbggenerated
     */
    private BigDecimal cpMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.paid_time
     *
     * @mbggenerated
     */
    private Date paidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.paid_num
     *
     * @mbggenerated
     */
    private BigDecimal paidNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.sur_user
     *
     * @mbggenerated
     */
    private String surUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.sur_time
     *
     * @mbggenerated
     */
    private Date surTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.del_user
     *
     * @mbggenerated
     */
    private String delUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.del_time
     *
     * @mbggenerated
     */
    private Date delTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.m_paid
     *
     * @mbggenerated
     */
    private BigDecimal mPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cpm_paid
     *
     * @mbggenerated
     */
    private BigDecimal cpmPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.se_no
     *
     * @mbggenerated
     */
    private String seNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cm_paid
     *
     * @mbggenerated
     */
    private BigDecimal cmPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.back_paid
     *
     * @mbggenerated
     */
    private BigDecimal backPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.back_paid_rate
     *
     * @mbggenerated
     */
    private BigDecimal backPaidRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.pback_paid
     *
     * @mbggenerated
     */
    private BigDecimal pbackPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.entrust_paid
     *
     * @mbggenerated
     */
    private BigDecimal entrustPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.entrust_paid_rate
     *
     * @mbggenerated
     */
    private BigDecimal entrustPaidRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.last_debt_m
     *
     * @mbggenerated
     */
    private BigDecimal lastDebtM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.left_amt
     *
     * @mbggenerated
     */
    private BigDecimal leftAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.create_emp_id
     *
     * @mbggenerated
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.modify_emp_id
     *
     * @mbggenerated
     */
    private String modifyEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.is_derate
     *
     * @mbggenerated
     */
    private String isDerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.in_derate
     *
     * @mbggenerated
     */
    private BigDecimal inDerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.out_derate
     *
     * @mbggenerated
     */
    private BigDecimal outDerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.cancel_reason
     *
     * @mbggenerated
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.repay_type
     *
     * @mbggenerated
     */
    private String repayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.operate_emp_id
     *
     * @mbggenerated
     */
    private String operateEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.operate_time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_paid.sur_remark
     *
     * @mbggenerated
     */
    private String surRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_paid
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.id
     *
     * @return the value of case_paid.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.id
     *
     * @param id the value for case_paid.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.state
     *
     * @return the value of case_paid.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.state
     *
     * @param state the value for case_paid.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.case_id
     *
     * @return the value of case_paid.case_id
     *
     * @mbggenerated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.case_id
     *
     * @param caseId the value for case_paid.case_id
     *
     * @mbggenerated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.ptp_time
     *
     * @return the value of case_paid.ptp_time
     *
     * @mbggenerated
     */
    public Date getPtpTime() {
        return ptpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.ptp_time
     *
     * @param ptpTime the value for case_paid.ptp_time
     *
     * @mbggenerated
     */
    public void setPtpTime(Date ptpTime) {
        this.ptpTime = ptpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.ptp_money
     *
     * @return the value of case_paid.ptp_money
     *
     * @mbggenerated
     */
    public BigDecimal getPtpMoney() {
        return ptpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.ptp_money
     *
     * @param ptpMoney the value for case_paid.ptp_money
     *
     * @mbggenerated
     */
    public void setPtpMoney(BigDecimal ptpMoney) {
        this.ptpMoney = ptpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cp_time
     *
     * @return the value of case_paid.cp_time
     *
     * @mbggenerated
     */
    public Date getCpTime() {
        return cpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cp_time
     *
     * @param cpTime the value for case_paid.cp_time
     *
     * @mbggenerated
     */
    public void setCpTime(Date cpTime) {
        this.cpTime = cpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cp_money
     *
     * @return the value of case_paid.cp_money
     *
     * @mbggenerated
     */
    public BigDecimal getCpMoney() {
        return cpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cp_money
     *
     * @param cpMoney the value for case_paid.cp_money
     *
     * @mbggenerated
     */
    public void setCpMoney(BigDecimal cpMoney) {
        this.cpMoney = cpMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.paid_time
     *
     * @return the value of case_paid.paid_time
     *
     * @mbggenerated
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.paid_time
     *
     * @param paidTime the value for case_paid.paid_time
     *
     * @mbggenerated
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.paid_num
     *
     * @return the value of case_paid.paid_num
     *
     * @mbggenerated
     */
    public BigDecimal getPaidNum() {
        return paidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.paid_num
     *
     * @param paidNum the value for case_paid.paid_num
     *
     * @mbggenerated
     */
    public void setPaidNum(BigDecimal paidNum) {
        this.paidNum = paidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.sur_user
     *
     * @return the value of case_paid.sur_user
     *
     * @mbggenerated
     */
    public String getSurUser() {
        return surUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.sur_user
     *
     * @param surUser the value for case_paid.sur_user
     *
     * @mbggenerated
     */
    public void setSurUser(String surUser) {
        this.surUser = surUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.sur_time
     *
     * @return the value of case_paid.sur_time
     *
     * @mbggenerated
     */
    public Date getSurTime() {
        return surTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.sur_time
     *
     * @param surTime the value for case_paid.sur_time
     *
     * @mbggenerated
     */
    public void setSurTime(Date surTime) {
        this.surTime = surTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.del_user
     *
     * @return the value of case_paid.del_user
     *
     * @mbggenerated
     */
    public String getDelUser() {
        return delUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.del_user
     *
     * @param delUser the value for case_paid.del_user
     *
     * @mbggenerated
     */
    public void setDelUser(String delUser) {
        this.delUser = delUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.del_time
     *
     * @return the value of case_paid.del_time
     *
     * @mbggenerated
     */
    public Date getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.del_time
     *
     * @param delTime the value for case_paid.del_time
     *
     * @mbggenerated
     */
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.m_paid
     *
     * @return the value of case_paid.m_paid
     *
     * @mbggenerated
     */
    public BigDecimal getmPaid() {
        return mPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.m_paid
     *
     * @param mPaid the value for case_paid.m_paid
     *
     * @mbggenerated
     */
    public void setmPaid(BigDecimal mPaid) {
        this.mPaid = mPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cpm_paid
     *
     * @return the value of case_paid.cpm_paid
     *
     * @mbggenerated
     */
    public BigDecimal getCpmPaid() {
        return cpmPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cpm_paid
     *
     * @param cpmPaid the value for case_paid.cpm_paid
     *
     * @mbggenerated
     */
    public void setCpmPaid(BigDecimal cpmPaid) {
        this.cpmPaid = cpmPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.se_no
     *
     * @return the value of case_paid.se_no
     *
     * @mbggenerated
     */
    public String getSeNo() {
        return seNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.se_no
     *
     * @param seNo the value for case_paid.se_no
     *
     * @mbggenerated
     */
    public void setSeNo(String seNo) {
        this.seNo = seNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cm_paid
     *
     * @return the value of case_paid.cm_paid
     *
     * @mbggenerated
     */
    public BigDecimal getCmPaid() {
        return cmPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cm_paid
     *
     * @param cmPaid the value for case_paid.cm_paid
     *
     * @mbggenerated
     */
    public void setCmPaid(BigDecimal cmPaid) {
        this.cmPaid = cmPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.back_paid
     *
     * @return the value of case_paid.back_paid
     *
     * @mbggenerated
     */
    public BigDecimal getBackPaid() {
        return backPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.back_paid
     *
     * @param backPaid the value for case_paid.back_paid
     *
     * @mbggenerated
     */
    public void setBackPaid(BigDecimal backPaid) {
        this.backPaid = backPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.back_paid_rate
     *
     * @return the value of case_paid.back_paid_rate
     *
     * @mbggenerated
     */
    public BigDecimal getBackPaidRate() {
        return backPaidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.back_paid_rate
     *
     * @param backPaidRate the value for case_paid.back_paid_rate
     *
     * @mbggenerated
     */
    public void setBackPaidRate(BigDecimal backPaidRate) {
        this.backPaidRate = backPaidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.pback_paid
     *
     * @return the value of case_paid.pback_paid
     *
     * @mbggenerated
     */
    public BigDecimal getPbackPaid() {
        return pbackPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.pback_paid
     *
     * @param pbackPaid the value for case_paid.pback_paid
     *
     * @mbggenerated
     */
    public void setPbackPaid(BigDecimal pbackPaid) {
        this.pbackPaid = pbackPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.entrust_paid
     *
     * @return the value of case_paid.entrust_paid
     *
     * @mbggenerated
     */
    public BigDecimal getEntrustPaid() {
        return entrustPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.entrust_paid
     *
     * @param entrustPaid the value for case_paid.entrust_paid
     *
     * @mbggenerated
     */
    public void setEntrustPaid(BigDecimal entrustPaid) {
        this.entrustPaid = entrustPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.entrust_paid_rate
     *
     * @return the value of case_paid.entrust_paid_rate
     *
     * @mbggenerated
     */
    public BigDecimal getEntrustPaidRate() {
        return entrustPaidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.entrust_paid_rate
     *
     * @param entrustPaidRate the value for case_paid.entrust_paid_rate
     *
     * @mbggenerated
     */
    public void setEntrustPaidRate(BigDecimal entrustPaidRate) {
        this.entrustPaidRate = entrustPaidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.last_debt_m
     *
     * @return the value of case_paid.last_debt_m
     *
     * @mbggenerated
     */
    public BigDecimal getLastDebtM() {
        return lastDebtM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.last_debt_m
     *
     * @param lastDebtM the value for case_paid.last_debt_m
     *
     * @mbggenerated
     */
    public void setLastDebtM(BigDecimal lastDebtM) {
        this.lastDebtM = lastDebtM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.left_amt
     *
     * @return the value of case_paid.left_amt
     *
     * @mbggenerated
     */
    public BigDecimal getLeftAmt() {
        return leftAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.left_amt
     *
     * @param leftAmt the value for case_paid.left_amt
     *
     * @mbggenerated
     */
    public void setLeftAmt(BigDecimal leftAmt) {
        this.leftAmt = leftAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.create_emp_id
     *
     * @return the value of case_paid.create_emp_id
     *
     * @mbggenerated
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.create_emp_id
     *
     * @param createEmpId the value for case_paid.create_emp_id
     *
     * @mbggenerated
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.create_time
     *
     * @return the value of case_paid.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.create_time
     *
     * @param createTime the value for case_paid.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.modify_emp_id
     *
     * @return the value of case_paid.modify_emp_id
     *
     * @mbggenerated
     */
    public String getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.modify_emp_id
     *
     * @param modifyEmpId the value for case_paid.modify_emp_id
     *
     * @mbggenerated
     */
    public void setModifyEmpId(String modifyEmpId) {
        this.modifyEmpId = modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.modify_time
     *
     * @return the value of case_paid.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.modify_time
     *
     * @param modifyTime the value for case_paid.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.version
     *
     * @return the value of case_paid.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.version
     *
     * @param version the value for case_paid.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.is_derate
     *
     * @return the value of case_paid.is_derate
     *
     * @mbggenerated
     */
    public String getIsDerate() {
        return isDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.is_derate
     *
     * @param isDerate the value for case_paid.is_derate
     *
     * @mbggenerated
     */
    public void setIsDerate(String isDerate) {
        this.isDerate = isDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.in_derate
     *
     * @return the value of case_paid.in_derate
     *
     * @mbggenerated
     */
    public BigDecimal getInDerate() {
        return inDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.in_derate
     *
     * @param inDerate the value for case_paid.in_derate
     *
     * @mbggenerated
     */
    public void setInDerate(BigDecimal inDerate) {
        this.inDerate = inDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.out_derate
     *
     * @return the value of case_paid.out_derate
     *
     * @mbggenerated
     */
    public BigDecimal getOutDerate() {
        return outDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.out_derate
     *
     * @param outDerate the value for case_paid.out_derate
     *
     * @mbggenerated
     */
    public void setOutDerate(BigDecimal outDerate) {
        this.outDerate = outDerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.cancel_reason
     *
     * @return the value of case_paid.cancel_reason
     *
     * @mbggenerated
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.cancel_reason
     *
     * @param cancelReason the value for case_paid.cancel_reason
     *
     * @mbggenerated
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.repay_type
     *
     * @return the value of case_paid.repay_type
     *
     * @mbggenerated
     */
    public String getRepayType() {
        return repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.repay_type
     *
     * @param repayType the value for case_paid.repay_type
     *
     * @mbggenerated
     */
    public void setRepayType(String repayType) {
        this.repayType = repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.operate_emp_id
     *
     * @return the value of case_paid.operate_emp_id
     *
     * @mbggenerated
     */
    public String getOperateEmpId() {
        return operateEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.operate_emp_id
     *
     * @param operateEmpId the value for case_paid.operate_emp_id
     *
     * @mbggenerated
     */
    public void setOperateEmpId(String operateEmpId) {
        this.operateEmpId = operateEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.operate_time
     *
     * @return the value of case_paid.operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.operate_time
     *
     * @param operateTime the value for case_paid.operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_paid.sur_remark
     *
     * @return the value of case_paid.sur_remark
     *
     * @mbggenerated
     */
    public String getSurRemark() {
        return surRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_paid.sur_remark
     *
     * @param surRemark the value for case_paid.sur_remark
     *
     * @mbggenerated
     */
    public void setSurRemark(String surRemark) {
        this.surRemark = surRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CasePaid other = (CasePaid) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCaseId() == null ? other.getCaseId() == null : this.getCaseId().equals(other.getCaseId()))
            && (this.getPtpTime() == null ? other.getPtpTime() == null : this.getPtpTime().equals(other.getPtpTime()))
            && (this.getPtpMoney() == null ? other.getPtpMoney() == null : this.getPtpMoney().equals(other.getPtpMoney()))
            && (this.getCpTime() == null ? other.getCpTime() == null : this.getCpTime().equals(other.getCpTime()))
            && (this.getCpMoney() == null ? other.getCpMoney() == null : this.getCpMoney().equals(other.getCpMoney()))
            && (this.getPaidTime() == null ? other.getPaidTime() == null : this.getPaidTime().equals(other.getPaidTime()))
            && (this.getPaidNum() == null ? other.getPaidNum() == null : this.getPaidNum().equals(other.getPaidNum()))
            && (this.getSurUser() == null ? other.getSurUser() == null : this.getSurUser().equals(other.getSurUser()))
            && (this.getSurTime() == null ? other.getSurTime() == null : this.getSurTime().equals(other.getSurTime()))
            && (this.getDelUser() == null ? other.getDelUser() == null : this.getDelUser().equals(other.getDelUser()))
            && (this.getDelTime() == null ? other.getDelTime() == null : this.getDelTime().equals(other.getDelTime()))
            && (this.getmPaid() == null ? other.getmPaid() == null : this.getmPaid().equals(other.getmPaid()))
            && (this.getCpmPaid() == null ? other.getCpmPaid() == null : this.getCpmPaid().equals(other.getCpmPaid()))
            && (this.getSeNo() == null ? other.getSeNo() == null : this.getSeNo().equals(other.getSeNo()))
            && (this.getCmPaid() == null ? other.getCmPaid() == null : this.getCmPaid().equals(other.getCmPaid()))
            && (this.getBackPaid() == null ? other.getBackPaid() == null : this.getBackPaid().equals(other.getBackPaid()))
            && (this.getBackPaidRate() == null ? other.getBackPaidRate() == null : this.getBackPaidRate().equals(other.getBackPaidRate()))
            && (this.getPbackPaid() == null ? other.getPbackPaid() == null : this.getPbackPaid().equals(other.getPbackPaid()))
            && (this.getEntrustPaid() == null ? other.getEntrustPaid() == null : this.getEntrustPaid().equals(other.getEntrustPaid()))
            && (this.getEntrustPaidRate() == null ? other.getEntrustPaidRate() == null : this.getEntrustPaidRate().equals(other.getEntrustPaidRate()))
            && (this.getLastDebtM() == null ? other.getLastDebtM() == null : this.getLastDebtM().equals(other.getLastDebtM()))
            && (this.getLeftAmt() == null ? other.getLeftAmt() == null : this.getLeftAmt().equals(other.getLeftAmt()))
            && (this.getCreateEmpId() == null ? other.getCreateEmpId() == null : this.getCreateEmpId().equals(other.getCreateEmpId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyEmpId() == null ? other.getModifyEmpId() == null : this.getModifyEmpId().equals(other.getModifyEmpId()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getIsDerate() == null ? other.getIsDerate() == null : this.getIsDerate().equals(other.getIsDerate()))
            && (this.getInDerate() == null ? other.getInDerate() == null : this.getInDerate().equals(other.getInDerate()))
            && (this.getOutDerate() == null ? other.getOutDerate() == null : this.getOutDerate().equals(other.getOutDerate()))
            && (this.getCancelReason() == null ? other.getCancelReason() == null : this.getCancelReason().equals(other.getCancelReason()))
            && (this.getRepayType() == null ? other.getRepayType() == null : this.getRepayType().equals(other.getRepayType()))
            && (this.getOperateEmpId() == null ? other.getOperateEmpId() == null : this.getOperateEmpId().equals(other.getOperateEmpId()))
            && (this.getOperateTime() == null ? other.getOperateTime() == null : this.getOperateTime().equals(other.getOperateTime()))
            && (this.getSurRemark() == null ? other.getSurRemark() == null : this.getSurRemark().equals(other.getSurRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCaseId() == null) ? 0 : getCaseId().hashCode());
        result = prime * result + ((getPtpTime() == null) ? 0 : getPtpTime().hashCode());
        result = prime * result + ((getPtpMoney() == null) ? 0 : getPtpMoney().hashCode());
        result = prime * result + ((getCpTime() == null) ? 0 : getCpTime().hashCode());
        result = prime * result + ((getCpMoney() == null) ? 0 : getCpMoney().hashCode());
        result = prime * result + ((getPaidTime() == null) ? 0 : getPaidTime().hashCode());
        result = prime * result + ((getPaidNum() == null) ? 0 : getPaidNum().hashCode());
        result = prime * result + ((getSurUser() == null) ? 0 : getSurUser().hashCode());
        result = prime * result + ((getSurTime() == null) ? 0 : getSurTime().hashCode());
        result = prime * result + ((getDelUser() == null) ? 0 : getDelUser().hashCode());
        result = prime * result + ((getDelTime() == null) ? 0 : getDelTime().hashCode());
        result = prime * result + ((getmPaid() == null) ? 0 : getmPaid().hashCode());
        result = prime * result + ((getCpmPaid() == null) ? 0 : getCpmPaid().hashCode());
        result = prime * result + ((getSeNo() == null) ? 0 : getSeNo().hashCode());
        result = prime * result + ((getCmPaid() == null) ? 0 : getCmPaid().hashCode());
        result = prime * result + ((getBackPaid() == null) ? 0 : getBackPaid().hashCode());
        result = prime * result + ((getBackPaidRate() == null) ? 0 : getBackPaidRate().hashCode());
        result = prime * result + ((getPbackPaid() == null) ? 0 : getPbackPaid().hashCode());
        result = prime * result + ((getEntrustPaid() == null) ? 0 : getEntrustPaid().hashCode());
        result = prime * result + ((getEntrustPaidRate() == null) ? 0 : getEntrustPaidRate().hashCode());
        result = prime * result + ((getLastDebtM() == null) ? 0 : getLastDebtM().hashCode());
        result = prime * result + ((getLeftAmt() == null) ? 0 : getLeftAmt().hashCode());
        result = prime * result + ((getCreateEmpId() == null) ? 0 : getCreateEmpId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyEmpId() == null) ? 0 : getModifyEmpId().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getIsDerate() == null) ? 0 : getIsDerate().hashCode());
        result = prime * result + ((getInDerate() == null) ? 0 : getInDerate().hashCode());
        result = prime * result + ((getOutDerate() == null) ? 0 : getOutDerate().hashCode());
        result = prime * result + ((getCancelReason() == null) ? 0 : getCancelReason().hashCode());
        result = prime * result + ((getRepayType() == null) ? 0 : getRepayType().hashCode());
        result = prime * result + ((getOperateEmpId() == null) ? 0 : getOperateEmpId().hashCode());
        result = prime * result + ((getOperateTime() == null) ? 0 : getOperateTime().hashCode());
        result = prime * result + ((getSurRemark() == null) ? 0 : getSurRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", state=").append(state);
        sb.append(", caseId=").append(caseId);
        sb.append(", ptpTime=").append(ptpTime);
        sb.append(", ptpMoney=").append(ptpMoney);
        sb.append(", cpTime=").append(cpTime);
        sb.append(", cpMoney=").append(cpMoney);
        sb.append(", paidTime=").append(paidTime);
        sb.append(", paidNum=").append(paidNum);
        sb.append(", surUser=").append(surUser);
        sb.append(", surTime=").append(surTime);
        sb.append(", delUser=").append(delUser);
        sb.append(", delTime=").append(delTime);
        sb.append(", mPaid=").append(mPaid);
        sb.append(", cpmPaid=").append(cpmPaid);
        sb.append(", seNo=").append(seNo);
        sb.append(", cmPaid=").append(cmPaid);
        sb.append(", backPaid=").append(backPaid);
        sb.append(", backPaidRate=").append(backPaidRate);
        sb.append(", pbackPaid=").append(pbackPaid);
        sb.append(", entrustPaid=").append(entrustPaid);
        sb.append(", entrustPaidRate=").append(entrustPaidRate);
        sb.append(", lastDebtM=").append(lastDebtM);
        sb.append(", leftAmt=").append(leftAmt);
        sb.append(", createEmpId=").append(createEmpId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyEmpId=").append(modifyEmpId);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", version=").append(version);
        sb.append(", isDerate=").append(isDerate);
        sb.append(", inDerate=").append(inDerate);
        sb.append(", outDerate=").append(outDerate);
        sb.append(", cancelReason=").append(cancelReason);
        sb.append(", repayType=").append(repayType);
        sb.append(", operateEmpId=").append(operateEmpId);
        sb.append(", operateTime=").append(operateTime);
        sb.append(", surRemark=").append(surRemark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}