package com.atguigu.entities;

import java.io.Serializable;
import java.util.Date;

public class EmployeeInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.personal_id
     *
     * @mbggenerated
     */
    private String personalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.sex
     *
     * @mbggenerated
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.married
     *
     * @mbggenerated
     */
    private Boolean married;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.join_time
     *
     * @mbggenerated
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.position_id
     *
     * @mbggenerated
     */
    private String positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.org_id
     *
     * @mbggenerated
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.cc_login
     *
     * @mbggenerated
     */
    private String ccLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.cc_pwd
     *
     * @mbggenerated
     */
    private String ccPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.cc_server
     *
     * @mbggenerated
     */
    private String ccServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.cc_phone
     *
     * @mbggenerated
     */
    private String ccPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.contact_mode
     *
     * @mbggenerated
     */
    private String contactMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.id
     *
     * @return the value of employee_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.id
     *
     * @param id the value for employee_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.salt
     *
     * @return the value of employee_info.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.salt
     *
     * @param salt the value for employee_info.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.create_time
     *
     * @return the value of employee_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.create_time
     *
     * @param createTime the value for employee_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.modify_time
     *
     * @return the value of employee_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.modify_time
     *
     * @param modifyTime the value for employee_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.version
     *
     * @return the value of employee_info.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.version
     *
     * @param version the value for employee_info.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.number
     *
     * @return the value of employee_info.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.number
     *
     * @param number the value for employee_info.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.status
     *
     * @return the value of employee_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.status
     *
     * @param status the value for employee_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.user_name
     *
     * @return the value of employee_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.user_name
     *
     * @param userName the value for employee_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.personal_id
     *
     * @return the value of employee_info.personal_id
     *
     * @mbggenerated
     */
    public String getPersonalId() {
        return personalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.personal_id
     *
     * @param personalId the value for employee_info.personal_id
     *
     * @mbggenerated
     */
    public void setPersonalId(String personalId) {
        this.personalId = personalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.sex
     *
     * @return the value of employee_info.sex
     *
     * @mbggenerated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.sex
     *
     * @param sex the value for employee_info.sex
     *
     * @mbggenerated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.birthday
     *
     * @return the value of employee_info.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.birthday
     *
     * @param birthday the value for employee_info.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.nation
     *
     * @return the value of employee_info.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.nation
     *
     * @param nation the value for employee_info.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.password
     *
     * @return the value of employee_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.password
     *
     * @param password the value for employee_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.login_name
     *
     * @return the value of employee_info.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.login_name
     *
     * @param loginName the value for employee_info.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.married
     *
     * @return the value of employee_info.married
     *
     * @mbggenerated
     */
    public Boolean getMarried() {
        return married;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.married
     *
     * @param married the value for employee_info.married
     *
     * @mbggenerated
     */
    public void setMarried(Boolean married) {
        this.married = married;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.province
     *
     * @return the value of employee_info.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.province
     *
     * @param province the value for employee_info.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.city
     *
     * @return the value of employee_info.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.city
     *
     * @param city the value for employee_info.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.email
     *
     * @return the value of employee_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.email
     *
     * @param email the value for employee_info.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.join_time
     *
     * @return the value of employee_info.join_time
     *
     * @mbggenerated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.join_time
     *
     * @param joinTime the value for employee_info.join_time
     *
     * @mbggenerated
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.position_id
     *
     * @return the value of employee_info.position_id
     *
     * @mbggenerated
     */
    public String getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.position_id
     *
     * @param positionId the value for employee_info.position_id
     *
     * @mbggenerated
     */
    public void setPositionId(String positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.org_id
     *
     * @return the value of employee_info.org_id
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.org_id
     *
     * @param orgId the value for employee_info.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.cc_login
     *
     * @return the value of employee_info.cc_login
     *
     * @mbggenerated
     */
    public String getCcLogin() {
        return ccLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.cc_login
     *
     * @param ccLogin the value for employee_info.cc_login
     *
     * @mbggenerated
     */
    public void setCcLogin(String ccLogin) {
        this.ccLogin = ccLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.cc_pwd
     *
     * @return the value of employee_info.cc_pwd
     *
     * @mbggenerated
     */
    public String getCcPwd() {
        return ccPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.cc_pwd
     *
     * @param ccPwd the value for employee_info.cc_pwd
     *
     * @mbggenerated
     */
    public void setCcPwd(String ccPwd) {
        this.ccPwd = ccPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.cc_server
     *
     * @return the value of employee_info.cc_server
     *
     * @mbggenerated
     */
    public String getCcServer() {
        return ccServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.cc_server
     *
     * @param ccServer the value for employee_info.cc_server
     *
     * @mbggenerated
     */
    public void setCcServer(String ccServer) {
        this.ccServer = ccServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.cc_phone
     *
     * @return the value of employee_info.cc_phone
     *
     * @mbggenerated
     */
    public String getCcPhone() {
        return ccPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.cc_phone
     *
     * @param ccPhone the value for employee_info.cc_phone
     *
     * @mbggenerated
     */
    public void setCcPhone(String ccPhone) {
        this.ccPhone = ccPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.contact_mode
     *
     * @return the value of employee_info.contact_mode
     *
     * @mbggenerated
     */
    public String getContactMode() {
        return contactMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.contact_mode
     *
     * @param contactMode the value for employee_info.contact_mode
     *
     * @mbggenerated
     */
    public void setContactMode(String contactMode) {
        this.contactMode = contactMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EmployeeInfo other = (EmployeeInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getPersonalId() == null ? other.getPersonalId() == null : this.getPersonalId().equals(other.getPersonalId()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getNation() == null ? other.getNation() == null : this.getNation().equals(other.getNation()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getMarried() == null ? other.getMarried() == null : this.getMarried().equals(other.getMarried()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getJoinTime() == null ? other.getJoinTime() == null : this.getJoinTime().equals(other.getJoinTime()))
            && (this.getPositionId() == null ? other.getPositionId() == null : this.getPositionId().equals(other.getPositionId()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getCcLogin() == null ? other.getCcLogin() == null : this.getCcLogin().equals(other.getCcLogin()))
            && (this.getCcPwd() == null ? other.getCcPwd() == null : this.getCcPwd().equals(other.getCcPwd()))
            && (this.getCcServer() == null ? other.getCcServer() == null : this.getCcServer().equals(other.getCcServer()))
            && (this.getCcPhone() == null ? other.getCcPhone() == null : this.getCcPhone().equals(other.getCcPhone()))
            && (this.getContactMode() == null ? other.getContactMode() == null : this.getContactMode().equals(other.getContactMode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPersonalId() == null) ? 0 : getPersonalId().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getMarried() == null) ? 0 : getMarried().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getJoinTime() == null) ? 0 : getJoinTime().hashCode());
        result = prime * result + ((getPositionId() == null) ? 0 : getPositionId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getCcLogin() == null) ? 0 : getCcLogin().hashCode());
        result = prime * result + ((getCcPwd() == null) ? 0 : getCcPwd().hashCode());
        result = prime * result + ((getCcServer() == null) ? 0 : getCcServer().hashCode());
        result = prime * result + ((getCcPhone() == null) ? 0 : getCcPhone().hashCode());
        result = prime * result + ((getContactMode() == null) ? 0 : getContactMode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", salt=").append(salt);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", version=").append(version);
        sb.append(", number=").append(number);
        sb.append(", status=").append(status);
        sb.append(", userName=").append(userName);
        sb.append(", personalId=").append(personalId);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", nation=").append(nation);
        sb.append(", password=").append(password);
        sb.append(", loginName=").append(loginName);
        sb.append(", married=").append(married);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", email=").append(email);
        sb.append(", joinTime=").append(joinTime);
        sb.append(", positionId=").append(positionId);
        sb.append(", orgId=").append(orgId);
        sb.append(", ccLogin=").append(ccLogin);
        sb.append(", ccPwd=").append(ccPwd);
        sb.append(", ccServer=").append(ccServer);
        sb.append(", ccPhone=").append(ccPhone);
        sb.append(", contactMode=").append(contactMode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}