package com.atguigu.entities;

import java.io.Serializable;

public class CaseInfoWithBLOBs extends CaseInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_info.old_collec_record
     *
     * @mbggenerated
     */
    private String oldCollecRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_info.remain_history
     *
     * @mbggenerated
     */
    private String remainHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_info.remark1
     *
     * @mbggenerated
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_info.remark2
     *
     * @mbggenerated
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_info.collec_remark
     *
     * @mbggenerated
     */
    private String collecRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_info.cus_introduc
     *
     * @mbggenerated
     */
    private String cusIntroduc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_info.his_remark
     *
     * @mbggenerated
     */
    private String hisRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_info.old_collec_record
     *
     * @return the value of case_info.old_collec_record
     *
     * @mbggenerated
     */
    public String getOldCollecRecord() {
        return oldCollecRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_info.old_collec_record
     *
     * @param oldCollecRecord the value for case_info.old_collec_record
     *
     * @mbggenerated
     */
    public void setOldCollecRecord(String oldCollecRecord) {
        this.oldCollecRecord = oldCollecRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_info.remain_history
     *
     * @return the value of case_info.remain_history
     *
     * @mbggenerated
     */
    public String getRemainHistory() {
        return remainHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_info.remain_history
     *
     * @param remainHistory the value for case_info.remain_history
     *
     * @mbggenerated
     */
    public void setRemainHistory(String remainHistory) {
        this.remainHistory = remainHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_info.remark1
     *
     * @return the value of case_info.remark1
     *
     * @mbggenerated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_info.remark1
     *
     * @param remark1 the value for case_info.remark1
     *
     * @mbggenerated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_info.remark2
     *
     * @return the value of case_info.remark2
     *
     * @mbggenerated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_info.remark2
     *
     * @param remark2 the value for case_info.remark2
     *
     * @mbggenerated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_info.collec_remark
     *
     * @return the value of case_info.collec_remark
     *
     * @mbggenerated
     */
    public String getCollecRemark() {
        return collecRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_info.collec_remark
     *
     * @param collecRemark the value for case_info.collec_remark
     *
     * @mbggenerated
     */
    public void setCollecRemark(String collecRemark) {
        this.collecRemark = collecRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_info.cus_introduc
     *
     * @return the value of case_info.cus_introduc
     *
     * @mbggenerated
     */
    public String getCusIntroduc() {
        return cusIntroduc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_info.cus_introduc
     *
     * @param cusIntroduc the value for case_info.cus_introduc
     *
     * @mbggenerated
     */
    public void setCusIntroduc(String cusIntroduc) {
        this.cusIntroduc = cusIntroduc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_info.his_remark
     *
     * @return the value of case_info.his_remark
     *
     * @mbggenerated
     */
    public String getHisRemark() {
        return hisRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_info.his_remark
     *
     * @param hisRemark the value for case_info.his_remark
     *
     * @mbggenerated
     */
    public void setHisRemark(String hisRemark) {
        this.hisRemark = hisRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CaseInfoWithBLOBs other = (CaseInfoWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCaseCode() == null ? other.getCaseCode() == null : this.getCaseCode().equals(other.getCaseCode()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCollecStateId() == null ? other.getCollecStateId() == null : this.getCollecStateId().equals(other.getCollecStateId()))
            && (this.getVisitStateId() == null ? other.getVisitStateId() == null : this.getVisitStateId().equals(other.getVisitStateId()))
            && (this.getBatchId() == null ? other.getBatchId() == null : this.getBatchId().equals(other.getBatchId()))
            && (this.getCaseDate() == null ? other.getCaseDate() == null : this.getCaseDate().equals(other.getCaseDate()))
            && (this.getCaseBackdate() == null ? other.getCaseBackdate() == null : this.getCaseBackdate().equals(other.getCaseBackdate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getCusNo() == null ? other.getCusNo() == null : this.getCusNo().equals(other.getCusNo()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getAccountNo() == null ? other.getAccountNo() == null : this.getAccountNo().equals(other.getAccountNo()))
            && (this.getCaseAppNo() == null ? other.getCaseAppNo() == null : this.getCaseAppNo().equals(other.getCaseAppNo()))
            && (this.getCaseFileNo() == null ? other.getCaseFileNo() == null : this.getCaseFileNo().equals(other.getCaseFileNo()))
            && (this.getCaseName() == null ? other.getCaseName() == null : this.getCaseName().equals(other.getCaseName()))
            && (this.getCaseSex() == null ? other.getCaseSex() == null : this.getCaseSex().equals(other.getCaseSex()))
            && (this.getCaseIsMarriage() == null ? other.getCaseIsMarriage() == null : this.getCaseIsMarriage().equals(other.getCaseIsMarriage()))
            && (this.getCaseBirthday() == null ? other.getCaseBirthday() == null : this.getCaseBirthday().equals(other.getCaseBirthday()))
            && (this.getCaseAge() == null ? other.getCaseAge() == null : this.getCaseAge().equals(other.getCaseAge()))
            && (this.getProvinceId() == null ? other.getProvinceId() == null : this.getProvinceId().equals(other.getProvinceId()))
            && (this.getProvinceName() == null ? other.getProvinceName() == null : this.getProvinceName().equals(other.getProvinceName()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()))
            && (this.getDistrictId() == null ? other.getDistrictId() == null : this.getDistrictId().equals(other.getDistrictId()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
            && (this.getAreaName() == null ? other.getAreaName() == null : this.getAreaName().equals(other.getAreaName()))
            && (this.getBankAccount() == null ? other.getBankAccount() == null : this.getBankAccount().equals(other.getBankAccount()))
            && (this.getCaseHouseId() == null ? other.getCaseHouseId() == null : this.getCaseHouseId().equals(other.getCaseHouseId()))
            && (this.getCaseCard() == null ? other.getCaseCard() == null : this.getCaseCard().equals(other.getCaseCard()))
            && (this.getCaseNum() == null ? other.getCaseNum() == null : this.getCaseNum().equals(other.getCaseNum()))
            && (this.getCaseNumId() == null ? other.getCaseNumId() == null : this.getCaseNumId().equals(other.getCaseNumId()))
            && (this.getCasePosition() == null ? other.getCasePosition() == null : this.getCasePosition().equals(other.getCasePosition()))
            && (this.getCaseDepartment() == null ? other.getCaseDepartment() == null : this.getCaseDepartment().equals(other.getCaseDepartment()))
            && (this.getCasePositionLevel() == null ? other.getCasePositionLevel() == null : this.getCasePositionLevel().equals(other.getCasePositionLevel()))
            && (this.getAccountName() == null ? other.getAccountName() == null : this.getAccountName().equals(other.getAccountName()))
            && (this.getLendInstitution() == null ? other.getLendInstitution() == null : this.getLendInstitution().equals(other.getLendInstitution()))
            && (this.getPrincipal() == null ? other.getPrincipal() == null : this.getPrincipal().equals(other.getPrincipal()))
            && (this.getSurplusPrincipal() == null ? other.getSurplusPrincipal() == null : this.getSurplusPrincipal().equals(other.getSurplusPrincipal()))
            && (this.getBreach() == null ? other.getBreach() == null : this.getBreach().equals(other.getBreach()))
            && (this.getCaseMoney() == null ? other.getCaseMoney() == null : this.getCaseMoney().equals(other.getCaseMoney()))
            && (this.getCaseLastMoney() == null ? other.getCaseLastMoney() == null : this.getCaseLastMoney().equals(other.getCaseLastMoney()))
            && (this.getCaseLastDate() == null ? other.getCaseLastDate() == null : this.getCaseLastDate().equals(other.getCaseLastDate()))
            && (this.getAccountMoney() == null ? other.getAccountMoney() == null : this.getAccountMoney().equals(other.getAccountMoney()))
            && (this.getLoanContract() == null ? other.getLoanContract() == null : this.getLoanContract().equals(other.getLoanContract()))
            && (this.getLoanMoney() == null ? other.getLoanMoney() == null : this.getLoanMoney().equals(other.getLoanMoney()))
            && (this.getLoanRate() == null ? other.getLoanRate() == null : this.getLoanRate().equals(other.getLoanRate()))
            && (this.getLoanStartdate() == null ? other.getLoanStartdate() == null : this.getLoanStartdate().equals(other.getLoanStartdate()))
            && (this.getLoanEnddate() == null ? other.getLoanEnddate() == null : this.getLoanEnddate().equals(other.getLoanEnddate()))
            && (this.getContractMoney() == null ? other.getContractMoney() == null : this.getContractMoney().equals(other.getContractMoney()))
            && (this.getOverdueMoney() == null ? other.getOverdueMoney() == null : this.getOverdueMoney().equals(other.getOverdueMoney()))
            && (this.getOverduePrincipal() == null ? other.getOverduePrincipal() == null : this.getOverduePrincipal().equals(other.getOverduePrincipal()))
            && (this.getOverdueExpense() == null ? other.getOverdueExpense() == null : this.getOverdueExpense().equals(other.getOverdueExpense()))
            && (this.getOverdueAge() == null ? other.getOverdueAge() == null : this.getOverdueAge().equals(other.getOverdueAge()))
            && (this.getOverduePenalty() == null ? other.getOverduePenalty() == null : this.getOverduePenalty().equals(other.getOverduePenalty()))
            && (this.getOverdueInterest() == null ? other.getOverdueInterest() == null : this.getOverdueInterest().equals(other.getOverdueInterest()))
            && (this.getOverdueDays() == null ? other.getOverdueDays() == null : this.getOverdueDays().equals(other.getOverdueDays()))
            && (this.getOverdueDate() == null ? other.getOverdueDate() == null : this.getOverdueDate().equals(other.getOverdueDate()))
            && (this.getOverduePeriods() == null ? other.getOverduePeriods() == null : this.getOverduePeriods().equals(other.getOverduePeriods()))
            && (this.getOnceOverduePeriods() == null ? other.getOnceOverduePeriods() == null : this.getOnceOverduePeriods().equals(other.getOnceOverduePeriods()))
            && (this.getOverdueLoan() == null ? other.getOverdueLoan() == null : this.getOverdueLoan().equals(other.getOverdueLoan()))
            && (this.getOverduePrincipalBalance() == null ? other.getOverduePrincipalBalance() == null : this.getOverduePrincipalBalance().equals(other.getOverduePrincipalBalance()))
            && (this.getOverdueCompound() == null ? other.getOverdueCompound() == null : this.getOverdueCompound().equals(other.getOverdueCompound()))
            && (this.getSocialSecurityNo() == null ? other.getSocialSecurityNo() == null : this.getSocialSecurityNo().equals(other.getSocialSecurityNo()))
            && (this.getSocialCardNo() == null ? other.getSocialCardNo() == null : this.getSocialCardNo().equals(other.getSocialCardNo()))
            && (this.getAgentRate() == null ? other.getAgentRate() == null : this.getAgentRate().equals(other.getAgentRate()))
            && (this.getEntrustRate() == null ? other.getEntrustRate() == null : this.getEntrustRate().equals(other.getEntrustRate()))
            && (this.getCreditId() == null ? other.getCreditId() == null : this.getCreditId().equals(other.getCreditId()))
            && (this.getStayPeriods() == null ? other.getStayPeriods() == null : this.getStayPeriods().equals(other.getStayPeriods()))
            && (this.getMonthRepayment() == null ? other.getMonthRepayment() == null : this.getMonthRepayment().equals(other.getMonthRepayment()))
            && (this.getLastRepayment() == null ? other.getLastRepayment() == null : this.getLastRepayment().equals(other.getLastRepayment()))
            && (this.getStayPrincipal() == null ? other.getStayPrincipal() == null : this.getStayPrincipal().equals(other.getStayPrincipal()))
            && (this.getStayExpense() == null ? other.getStayExpense() == null : this.getStayExpense().equals(other.getStayExpense()))
            && (this.getStayInterest() == null ? other.getStayInterest() == null : this.getStayInterest().equals(other.getStayInterest()))
            && (this.getBill() == null ? other.getBill() == null : this.getBill().equals(other.getBill()))
            && (this.getRepaymentPeriods() == null ? other.getRepaymentPeriods() == null : this.getRepaymentPeriods().equals(other.getRepaymentPeriods()))
            && (this.getCommodity() == null ? other.getCommodity() == null : this.getCommodity().equals(other.getCommodity()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getCompanyPhone() == null ? other.getCompanyPhone() == null : this.getCompanyPhone().equals(other.getCompanyPhone()))
            && (this.getCompanyAddress() == null ? other.getCompanyAddress() == null : this.getCompanyAddress().equals(other.getCompanyAddress()))
            && (this.getCompanyZipcode() == null ? other.getCompanyZipcode() == null : this.getCompanyZipcode().equals(other.getCompanyZipcode()))
            && (this.getMobile1() == null ? other.getMobile1() == null : this.getMobile1().equals(other.getMobile1()))
            && (this.getMobile2() == null ? other.getMobile2() == null : this.getMobile2().equals(other.getMobile2()))
            && (this.getFamilyPhone() == null ? other.getFamilyPhone() == null : this.getFamilyPhone().equals(other.getFamilyPhone()))
            && (this.getFamilyAddress() == null ? other.getFamilyAddress() == null : this.getFamilyAddress().equals(other.getFamilyAddress()))
            && (this.getFamilyZipcode() == null ? other.getFamilyZipcode() == null : this.getFamilyZipcode().equals(other.getFamilyZipcode()))
            && (this.getDomicile() == null ? other.getDomicile() == null : this.getDomicile().equals(other.getDomicile()))
            && (this.getMarkId() == null ? other.getMarkId() == null : this.getMarkId().equals(other.getMarkId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getIsVerify() == null ? other.getIsVerify() == null : this.getIsVerify().equals(other.getIsVerify()))
            && (this.getVerifyDate() == null ? other.getVerifyDate() == null : this.getVerifyDate().equals(other.getVerifyDate()))
            && (this.getRepaymentType() == null ? other.getRepaymentType() == null : this.getRepaymentType().equals(other.getRepaymentType()))
            && (this.getProtocolNo() == null ? other.getProtocolNo() == null : this.getProtocolNo().equals(other.getProtocolNo()))
            && (this.getLoanArea() == null ? other.getLoanArea() == null : this.getLoanArea().equals(other.getLoanArea()))
            && (this.getActualLoanMoney() == null ? other.getActualLoanMoney() == null : this.getActualLoanMoney().equals(other.getActualLoanMoney()))
            && (this.getInterestMoney() == null ? other.getInterestMoney() == null : this.getInterestMoney().equals(other.getInterestMoney()))
            && (this.getPenaltyReference() == null ? other.getPenaltyReference() == null : this.getPenaltyReference().equals(other.getPenaltyReference()))
            && (this.getCompoundInterestReference() == null ? other.getCompoundInterestReference() == null : this.getCompoundInterestReference().equals(other.getCompoundInterestReference()))
            && (this.getQuotaNo() == null ? other.getQuotaNo() == null : this.getQuotaNo().equals(other.getQuotaNo()))
            && (this.getQuotaManager1() == null ? other.getQuotaManager1() == null : this.getQuotaManager1().equals(other.getQuotaManager1()))
            && (this.getQuotaManager2() == null ? other.getQuotaManager2() == null : this.getQuotaManager2().equals(other.getQuotaManager2()))
            && (this.getManagerPhone() == null ? other.getManagerPhone() == null : this.getManagerPhone().equals(other.getManagerPhone()))
            && (this.getCollateralNo() == null ? other.getCollateralNo() == null : this.getCollateralNo().equals(other.getCollateralNo()))
            && (this.getCollateralId() == null ? other.getCollateralId() == null : this.getCollateralId().equals(other.getCollateralId()))
            && (this.getCollateralName() == null ? other.getCollateralName() == null : this.getCollateralName().equals(other.getCollateralName()))
            && (this.getCollateralAddress() == null ? other.getCollateralAddress() == null : this.getCollateralAddress().equals(other.getCollateralAddress()))
            && (this.getCollateralEvalua() == null ? other.getCollateralEvalua() == null : this.getCollateralEvalua().equals(other.getCollateralEvalua()))
            && (this.getRepayDate() == null ? other.getRepayDate() == null : this.getRepayDate().equals(other.getRepayDate()))
            && (this.getTotalConstruc() == null ? other.getTotalConstruc() == null : this.getTotalConstruc().equals(other.getTotalConstruc()))
            && (this.getRegione() == null ? other.getRegione() == null : this.getRegione().equals(other.getRegione()))
            && (this.getSubCenter() == null ? other.getSubCenter() == null : this.getSubCenter().equals(other.getSubCenter()))
            && (this.getSalesDep() == null ? other.getSalesDep() == null : this.getSalesDep().equals(other.getSalesDep()))
            && (this.getConsultFee() == null ? other.getConsultFee() == null : this.getConsultFee().equals(other.getConsultFee()))
            && (this.getAuditFee() == null ? other.getAuditFee() == null : this.getAuditFee().equals(other.getAuditFee()))
            && (this.getServiceFee() == null ? other.getServiceFee() == null : this.getServiceFee().equals(other.getServiceFee()))
            && (this.getAdviserFee() == null ? other.getAdviserFee() == null : this.getAdviserFee().equals(other.getAdviserFee()))
            && (this.getFeeTotal() == null ? other.getFeeTotal() == null : this.getFeeTotal().equals(other.getFeeTotal()))
            && (this.getInitialRepay() == null ? other.getInitialRepay() == null : this.getInitialRepay().equals(other.getInitialRepay()))
            && (this.getDuePeriods() == null ? other.getDuePeriods() == null : this.getDuePeriods().equals(other.getDuePeriods()))
            && (this.getPenaltyDays() == null ? other.getPenaltyDays() == null : this.getPenaltyDays().equals(other.getPenaltyDays()))
            && (this.getDebitBankCode() == null ? other.getDebitBankCode() == null : this.getDebitBankCode().equals(other.getDebitBankCode()))
            && (this.getDebitBankName() == null ? other.getDebitBankName() == null : this.getDebitBankName().equals(other.getDebitBankName()))
            && (this.getDebitAccount() == null ? other.getDebitAccount() == null : this.getDebitAccount().equals(other.getDebitAccount()))
            && (this.getReliefPolicy() == null ? other.getReliefPolicy() == null : this.getReliefPolicy().equals(other.getReliefPolicy()))
            && (this.getCaseAssignedId() == null ? other.getCaseAssignedId() == null : this.getCaseAssignedId().equals(other.getCaseAssignedId()))
            && (this.getCaseAssignId() == null ? other.getCaseAssignId() == null : this.getCaseAssignId().equals(other.getCaseAssignId()))
            && (this.getCaseAssignName() == null ? other.getCaseAssignName() == null : this.getCaseAssignName().equals(other.getCaseAssignName()))
            && (this.getCaseAssignTime() == null ? other.getCaseAssignTime() == null : this.getCaseAssignTime().equals(other.getCaseAssignTime()))
            && (this.getCreateEmpId() == null ? other.getCreateEmpId() == null : this.getCreateEmpId().equals(other.getCreateEmpId()))
            && (this.getModifyEmpId() == null ? other.getModifyEmpId() == null : this.getModifyEmpId().equals(other.getModifyEmpId()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getNextFollowTime() == null ? other.getNextFollowTime() == null : this.getNextFollowTime().equals(other.getNextFollowTime()))
            && (this.getNextFollowState() == null ? other.getNextFollowState() == null : this.getNextFollowState().equals(other.getNextFollowState()))
            && (this.getLastPhoneTime() == null ? other.getLastPhoneTime() == null : this.getLastPhoneTime().equals(other.getLastPhoneTime()))
            && (this.getIsUpdate() == null ? other.getIsUpdate() == null : this.getIsUpdate().equals(other.getIsUpdate()))
            && (this.getHandle() == null ? other.getHandle() == null : this.getHandle().equals(other.getHandle()))
            && (this.getInDerate() == null ? other.getInDerate() == null : this.getInDerate().equals(other.getInDerate()))
            && (this.getOutDerate() == null ? other.getOutDerate() == null : this.getOutDerate().equals(other.getOutDerate()))
            && (this.getColor() == null ? other.getColor() == null : this.getColor().equals(other.getColor()))
            && (this.getCaseWarn() == null ? other.getCaseWarn() == null : this.getCaseWarn().equals(other.getCaseWarn()))
            && (this.getStartCardDate() == null ? other.getStartCardDate() == null : this.getStartCardDate().equals(other.getStartCardDate()))
            && (this.getStopCardDate() == null ? other.getStopCardDate() == null : this.getStopCardDate().equals(other.getStopCardDate()))
            && (this.getCreditLimit() == null ? other.getCreditLimit() == null : this.getCreditLimit().equals(other.getCreditLimit()))
            && (this.getPolicyExpire() == null ? other.getPolicyExpire() == null : this.getPolicyExpire().equals(other.getPolicyExpire()))
            && (this.getCollecType() == null ? other.getCollecType() == null : this.getCollecType().equals(other.getCollecType()))
            && (this.getLateFee() == null ? other.getLateFee() == null : this.getLateFee().equals(other.getLateFee()))
            && (this.getDomicileZipcode() == null ? other.getDomicileZipcode() == null : this.getDomicileZipcode().equals(other.getDomicileZipcode()))
            && (this.getBillAddress() == null ? other.getBillAddress() == null : this.getBillAddress().equals(other.getBillAddress()))
            && (this.getBillZipcode() == null ? other.getBillZipcode() == null : this.getBillZipcode().equals(other.getBillZipcode()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getRepaymentTerm() == null ? other.getRepaymentTerm() == null : this.getRepaymentTerm().equals(other.getRepaymentTerm()))
            && (this.getOldCollecRecord() == null ? other.getOldCollecRecord() == null : this.getOldCollecRecord().equals(other.getOldCollecRecord()))
            && (this.getRemainHistory() == null ? other.getRemainHistory() == null : this.getRemainHistory().equals(other.getRemainHistory()))
            && (this.getRemark1() == null ? other.getRemark1() == null : this.getRemark1().equals(other.getRemark1()))
            && (this.getRemark2() == null ? other.getRemark2() == null : this.getRemark2().equals(other.getRemark2()))
            && (this.getCollecRemark() == null ? other.getCollecRemark() == null : this.getCollecRemark().equals(other.getCollecRemark()))
            && (this.getCusIntroduc() == null ? other.getCusIntroduc() == null : this.getCusIntroduc().equals(other.getCusIntroduc()))
            && (this.getHisRemark() == null ? other.getHisRemark() == null : this.getHisRemark().equals(other.getHisRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCaseCode() == null) ? 0 : getCaseCode().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCollecStateId() == null) ? 0 : getCollecStateId().hashCode());
        result = prime * result + ((getVisitStateId() == null) ? 0 : getVisitStateId().hashCode());
        result = prime * result + ((getBatchId() == null) ? 0 : getBatchId().hashCode());
        result = prime * result + ((getCaseDate() == null) ? 0 : getCaseDate().hashCode());
        result = prime * result + ((getCaseBackdate() == null) ? 0 : getCaseBackdate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getCusNo() == null) ? 0 : getCusNo().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getAccountNo() == null) ? 0 : getAccountNo().hashCode());
        result = prime * result + ((getCaseAppNo() == null) ? 0 : getCaseAppNo().hashCode());
        result = prime * result + ((getCaseFileNo() == null) ? 0 : getCaseFileNo().hashCode());
        result = prime * result + ((getCaseName() == null) ? 0 : getCaseName().hashCode());
        result = prime * result + ((getCaseSex() == null) ? 0 : getCaseSex().hashCode());
        result = prime * result + ((getCaseIsMarriage() == null) ? 0 : getCaseIsMarriage().hashCode());
        result = prime * result + ((getCaseBirthday() == null) ? 0 : getCaseBirthday().hashCode());
        result = prime * result + ((getCaseAge() == null) ? 0 : getCaseAge().hashCode());
        result = prime * result + ((getProvinceId() == null) ? 0 : getProvinceId().hashCode());
        result = prime * result + ((getProvinceName() == null) ? 0 : getProvinceName().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        result = prime * result + ((getDistrictId() == null) ? 0 : getDistrictId().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getAreaName() == null) ? 0 : getAreaName().hashCode());
        result = prime * result + ((getBankAccount() == null) ? 0 : getBankAccount().hashCode());
        result = prime * result + ((getCaseHouseId() == null) ? 0 : getCaseHouseId().hashCode());
        result = prime * result + ((getCaseCard() == null) ? 0 : getCaseCard().hashCode());
        result = prime * result + ((getCaseNum() == null) ? 0 : getCaseNum().hashCode());
        result = prime * result + ((getCaseNumId() == null) ? 0 : getCaseNumId().hashCode());
        result = prime * result + ((getCasePosition() == null) ? 0 : getCasePosition().hashCode());
        result = prime * result + ((getCaseDepartment() == null) ? 0 : getCaseDepartment().hashCode());
        result = prime * result + ((getCasePositionLevel() == null) ? 0 : getCasePositionLevel().hashCode());
        result = prime * result + ((getAccountName() == null) ? 0 : getAccountName().hashCode());
        result = prime * result + ((getLendInstitution() == null) ? 0 : getLendInstitution().hashCode());
        result = prime * result + ((getPrincipal() == null) ? 0 : getPrincipal().hashCode());
        result = prime * result + ((getSurplusPrincipal() == null) ? 0 : getSurplusPrincipal().hashCode());
        result = prime * result + ((getBreach() == null) ? 0 : getBreach().hashCode());
        result = prime * result + ((getCaseMoney() == null) ? 0 : getCaseMoney().hashCode());
        result = prime * result + ((getCaseLastMoney() == null) ? 0 : getCaseLastMoney().hashCode());
        result = prime * result + ((getCaseLastDate() == null) ? 0 : getCaseLastDate().hashCode());
        result = prime * result + ((getAccountMoney() == null) ? 0 : getAccountMoney().hashCode());
        result = prime * result + ((getLoanContract() == null) ? 0 : getLoanContract().hashCode());
        result = prime * result + ((getLoanMoney() == null) ? 0 : getLoanMoney().hashCode());
        result = prime * result + ((getLoanRate() == null) ? 0 : getLoanRate().hashCode());
        result = prime * result + ((getLoanStartdate() == null) ? 0 : getLoanStartdate().hashCode());
        result = prime * result + ((getLoanEnddate() == null) ? 0 : getLoanEnddate().hashCode());
        result = prime * result + ((getContractMoney() == null) ? 0 : getContractMoney().hashCode());
        result = prime * result + ((getOverdueMoney() == null) ? 0 : getOverdueMoney().hashCode());
        result = prime * result + ((getOverduePrincipal() == null) ? 0 : getOverduePrincipal().hashCode());
        result = prime * result + ((getOverdueExpense() == null) ? 0 : getOverdueExpense().hashCode());
        result = prime * result + ((getOverdueAge() == null) ? 0 : getOverdueAge().hashCode());
        result = prime * result + ((getOverduePenalty() == null) ? 0 : getOverduePenalty().hashCode());
        result = prime * result + ((getOverdueInterest() == null) ? 0 : getOverdueInterest().hashCode());
        result = prime * result + ((getOverdueDays() == null) ? 0 : getOverdueDays().hashCode());
        result = prime * result + ((getOverdueDate() == null) ? 0 : getOverdueDate().hashCode());
        result = prime * result + ((getOverduePeriods() == null) ? 0 : getOverduePeriods().hashCode());
        result = prime * result + ((getOnceOverduePeriods() == null) ? 0 : getOnceOverduePeriods().hashCode());
        result = prime * result + ((getOverdueLoan() == null) ? 0 : getOverdueLoan().hashCode());
        result = prime * result + ((getOverduePrincipalBalance() == null) ? 0 : getOverduePrincipalBalance().hashCode());
        result = prime * result + ((getOverdueCompound() == null) ? 0 : getOverdueCompound().hashCode());
        result = prime * result + ((getSocialSecurityNo() == null) ? 0 : getSocialSecurityNo().hashCode());
        result = prime * result + ((getSocialCardNo() == null) ? 0 : getSocialCardNo().hashCode());
        result = prime * result + ((getAgentRate() == null) ? 0 : getAgentRate().hashCode());
        result = prime * result + ((getEntrustRate() == null) ? 0 : getEntrustRate().hashCode());
        result = prime * result + ((getCreditId() == null) ? 0 : getCreditId().hashCode());
        result = prime * result + ((getStayPeriods() == null) ? 0 : getStayPeriods().hashCode());
        result = prime * result + ((getMonthRepayment() == null) ? 0 : getMonthRepayment().hashCode());
        result = prime * result + ((getLastRepayment() == null) ? 0 : getLastRepayment().hashCode());
        result = prime * result + ((getStayPrincipal() == null) ? 0 : getStayPrincipal().hashCode());
        result = prime * result + ((getStayExpense() == null) ? 0 : getStayExpense().hashCode());
        result = prime * result + ((getStayInterest() == null) ? 0 : getStayInterest().hashCode());
        result = prime * result + ((getBill() == null) ? 0 : getBill().hashCode());
        result = prime * result + ((getRepaymentPeriods() == null) ? 0 : getRepaymentPeriods().hashCode());
        result = prime * result + ((getCommodity() == null) ? 0 : getCommodity().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getCompanyPhone() == null) ? 0 : getCompanyPhone().hashCode());
        result = prime * result + ((getCompanyAddress() == null) ? 0 : getCompanyAddress().hashCode());
        result = prime * result + ((getCompanyZipcode() == null) ? 0 : getCompanyZipcode().hashCode());
        result = prime * result + ((getMobile1() == null) ? 0 : getMobile1().hashCode());
        result = prime * result + ((getMobile2() == null) ? 0 : getMobile2().hashCode());
        result = prime * result + ((getFamilyPhone() == null) ? 0 : getFamilyPhone().hashCode());
        result = prime * result + ((getFamilyAddress() == null) ? 0 : getFamilyAddress().hashCode());
        result = prime * result + ((getFamilyZipcode() == null) ? 0 : getFamilyZipcode().hashCode());
        result = prime * result + ((getDomicile() == null) ? 0 : getDomicile().hashCode());
        result = prime * result + ((getMarkId() == null) ? 0 : getMarkId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getIsVerify() == null) ? 0 : getIsVerify().hashCode());
        result = prime * result + ((getVerifyDate() == null) ? 0 : getVerifyDate().hashCode());
        result = prime * result + ((getRepaymentType() == null) ? 0 : getRepaymentType().hashCode());
        result = prime * result + ((getProtocolNo() == null) ? 0 : getProtocolNo().hashCode());
        result = prime * result + ((getLoanArea() == null) ? 0 : getLoanArea().hashCode());
        result = prime * result + ((getActualLoanMoney() == null) ? 0 : getActualLoanMoney().hashCode());
        result = prime * result + ((getInterestMoney() == null) ? 0 : getInterestMoney().hashCode());
        result = prime * result + ((getPenaltyReference() == null) ? 0 : getPenaltyReference().hashCode());
        result = prime * result + ((getCompoundInterestReference() == null) ? 0 : getCompoundInterestReference().hashCode());
        result = prime * result + ((getQuotaNo() == null) ? 0 : getQuotaNo().hashCode());
        result = prime * result + ((getQuotaManager1() == null) ? 0 : getQuotaManager1().hashCode());
        result = prime * result + ((getQuotaManager2() == null) ? 0 : getQuotaManager2().hashCode());
        result = prime * result + ((getManagerPhone() == null) ? 0 : getManagerPhone().hashCode());
        result = prime * result + ((getCollateralNo() == null) ? 0 : getCollateralNo().hashCode());
        result = prime * result + ((getCollateralId() == null) ? 0 : getCollateralId().hashCode());
        result = prime * result + ((getCollateralName() == null) ? 0 : getCollateralName().hashCode());
        result = prime * result + ((getCollateralAddress() == null) ? 0 : getCollateralAddress().hashCode());
        result = prime * result + ((getCollateralEvalua() == null) ? 0 : getCollateralEvalua().hashCode());
        result = prime * result + ((getRepayDate() == null) ? 0 : getRepayDate().hashCode());
        result = prime * result + ((getTotalConstruc() == null) ? 0 : getTotalConstruc().hashCode());
        result = prime * result + ((getRegione() == null) ? 0 : getRegione().hashCode());
        result = prime * result + ((getSubCenter() == null) ? 0 : getSubCenter().hashCode());
        result = prime * result + ((getSalesDep() == null) ? 0 : getSalesDep().hashCode());
        result = prime * result + ((getConsultFee() == null) ? 0 : getConsultFee().hashCode());
        result = prime * result + ((getAuditFee() == null) ? 0 : getAuditFee().hashCode());
        result = prime * result + ((getServiceFee() == null) ? 0 : getServiceFee().hashCode());
        result = prime * result + ((getAdviserFee() == null) ? 0 : getAdviserFee().hashCode());
        result = prime * result + ((getFeeTotal() == null) ? 0 : getFeeTotal().hashCode());
        result = prime * result + ((getInitialRepay() == null) ? 0 : getInitialRepay().hashCode());
        result = prime * result + ((getDuePeriods() == null) ? 0 : getDuePeriods().hashCode());
        result = prime * result + ((getPenaltyDays() == null) ? 0 : getPenaltyDays().hashCode());
        result = prime * result + ((getDebitBankCode() == null) ? 0 : getDebitBankCode().hashCode());
        result = prime * result + ((getDebitBankName() == null) ? 0 : getDebitBankName().hashCode());
        result = prime * result + ((getDebitAccount() == null) ? 0 : getDebitAccount().hashCode());
        result = prime * result + ((getReliefPolicy() == null) ? 0 : getReliefPolicy().hashCode());
        result = prime * result + ((getCaseAssignedId() == null) ? 0 : getCaseAssignedId().hashCode());
        result = prime * result + ((getCaseAssignId() == null) ? 0 : getCaseAssignId().hashCode());
        result = prime * result + ((getCaseAssignName() == null) ? 0 : getCaseAssignName().hashCode());
        result = prime * result + ((getCaseAssignTime() == null) ? 0 : getCaseAssignTime().hashCode());
        result = prime * result + ((getCreateEmpId() == null) ? 0 : getCreateEmpId().hashCode());
        result = prime * result + ((getModifyEmpId() == null) ? 0 : getModifyEmpId().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getNextFollowTime() == null) ? 0 : getNextFollowTime().hashCode());
        result = prime * result + ((getNextFollowState() == null) ? 0 : getNextFollowState().hashCode());
        result = prime * result + ((getLastPhoneTime() == null) ? 0 : getLastPhoneTime().hashCode());
        result = prime * result + ((getIsUpdate() == null) ? 0 : getIsUpdate().hashCode());
        result = prime * result + ((getHandle() == null) ? 0 : getHandle().hashCode());
        result = prime * result + ((getInDerate() == null) ? 0 : getInDerate().hashCode());
        result = prime * result + ((getOutDerate() == null) ? 0 : getOutDerate().hashCode());
        result = prime * result + ((getColor() == null) ? 0 : getColor().hashCode());
        result = prime * result + ((getCaseWarn() == null) ? 0 : getCaseWarn().hashCode());
        result = prime * result + ((getStartCardDate() == null) ? 0 : getStartCardDate().hashCode());
        result = prime * result + ((getStopCardDate() == null) ? 0 : getStopCardDate().hashCode());
        result = prime * result + ((getCreditLimit() == null) ? 0 : getCreditLimit().hashCode());
        result = prime * result + ((getPolicyExpire() == null) ? 0 : getPolicyExpire().hashCode());
        result = prime * result + ((getCollecType() == null) ? 0 : getCollecType().hashCode());
        result = prime * result + ((getLateFee() == null) ? 0 : getLateFee().hashCode());
        result = prime * result + ((getDomicileZipcode() == null) ? 0 : getDomicileZipcode().hashCode());
        result = prime * result + ((getBillAddress() == null) ? 0 : getBillAddress().hashCode());
        result = prime * result + ((getBillZipcode() == null) ? 0 : getBillZipcode().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getRepaymentTerm() == null) ? 0 : getRepaymentTerm().hashCode());
        result = prime * result + ((getOldCollecRecord() == null) ? 0 : getOldCollecRecord().hashCode());
        result = prime * result + ((getRemainHistory() == null) ? 0 : getRemainHistory().hashCode());
        result = prime * result + ((getRemark1() == null) ? 0 : getRemark1().hashCode());
        result = prime * result + ((getRemark2() == null) ? 0 : getRemark2().hashCode());
        result = prime * result + ((getCollecRemark() == null) ? 0 : getCollecRemark().hashCode());
        result = prime * result + ((getCusIntroduc() == null) ? 0 : getCusIntroduc().hashCode());
        result = prime * result + ((getHisRemark() == null) ? 0 : getHisRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oldCollecRecord=").append(oldCollecRecord);
        sb.append(", remainHistory=").append(remainHistory);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", collecRemark=").append(collecRemark);
        sb.append(", cusIntroduc=").append(cusIntroduc);
        sb.append(", hisRemark=").append(hisRemark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}