package com.atguigu.entities;

import java.io.Serializable;
import java.util.Date;

public class Entrust implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.cooperate_date
     *
     * @mbggenerated
     */
    private Date cooperateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.service_hotline
     *
     * @mbggenerated
     */
    private String serviceHotline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.abutment_person
     *
     * @mbggenerated
     */
    private String abutmentPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.abutment_email
     *
     * @mbggenerated
     */
    private String abutmentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.abutment_phone
     *
     * @mbggenerated
     */
    private String abutmentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.case_frequency
     *
     * @mbggenerated
     */
    private String caseFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.effec_repay_period
     *
     * @mbggenerated
     */
    private String effecRepayPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.collec_nominal
     *
     * @mbggenerated
     */
    private String collecNominal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.collec_term
     *
     * @mbggenerated
     */
    private String collecTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.stay_require
     *
     * @mbggenerated
     */
    private String stayRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.back_require
     *
     * @mbggenerated
     */
    private String backRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.report_period
     *
     * @mbggenerated
     */
    private String reportPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.settlement_period
     *
     * @mbggenerated
     */
    private String settlementPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.repayment_method
     *
     * @mbggenerated
     */
    private String repaymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.discount_reduction
     *
     * @mbggenerated
     */
    private String discountReduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.period_repayment_require
     *
     * @mbggenerated
     */
    private String periodRepaymentRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.cancel_account
     *
     * @mbggenerated
     */
    private String cancelAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.resource_retrieve_require
     *
     * @mbggenerated
     */
    private String resourceRetrieveRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.collec_submit_require
     *
     * @mbggenerated
     */
    private String collecSubmitRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.complaint_handle_require
     *
     * @mbggenerated
     */
    private String complaintHandleRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.tape_submit_require
     *
     * @mbggenerated
     */
    private String tapeSubmitRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.data_destruc_require
     *
     * @mbggenerated
     */
    private String dataDestrucRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.letter_recovery_require
     *
     * @mbggenerated
     */
    private String letterRecoveryRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.report_require
     *
     * @mbggenerated
     */
    private String reportRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.cus_special_instruc
     *
     * @mbggenerated
     */
    private String cusSpecialInstruc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.contract_name
     *
     * @mbggenerated
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.create_emp_id
     *
     * @mbggenerated
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.create_emp_name
     *
     * @mbggenerated
     */
    private String createEmpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrust
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.id
     *
     * @return the value of entrust.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.id
     *
     * @param id the value for entrust.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.name
     *
     * @return the value of entrust.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.name
     *
     * @param name the value for entrust.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.code
     *
     * @return the value of entrust.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.code
     *
     * @param code the value for entrust.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.cooperate_date
     *
     * @return the value of entrust.cooperate_date
     *
     * @mbggenerated
     */
    public Date getCooperateDate() {
        return cooperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.cooperate_date
     *
     * @param cooperateDate the value for entrust.cooperate_date
     *
     * @mbggenerated
     */
    public void setCooperateDate(Date cooperateDate) {
        this.cooperateDate = cooperateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.address
     *
     * @return the value of entrust.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.address
     *
     * @param address the value for entrust.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.service_hotline
     *
     * @return the value of entrust.service_hotline
     *
     * @mbggenerated
     */
    public String getServiceHotline() {
        return serviceHotline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.service_hotline
     *
     * @param serviceHotline the value for entrust.service_hotline
     *
     * @mbggenerated
     */
    public void setServiceHotline(String serviceHotline) {
        this.serviceHotline = serviceHotline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.abutment_person
     *
     * @return the value of entrust.abutment_person
     *
     * @mbggenerated
     */
    public String getAbutmentPerson() {
        return abutmentPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.abutment_person
     *
     * @param abutmentPerson the value for entrust.abutment_person
     *
     * @mbggenerated
     */
    public void setAbutmentPerson(String abutmentPerson) {
        this.abutmentPerson = abutmentPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.abutment_email
     *
     * @return the value of entrust.abutment_email
     *
     * @mbggenerated
     */
    public String getAbutmentEmail() {
        return abutmentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.abutment_email
     *
     * @param abutmentEmail the value for entrust.abutment_email
     *
     * @mbggenerated
     */
    public void setAbutmentEmail(String abutmentEmail) {
        this.abutmentEmail = abutmentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.abutment_phone
     *
     * @return the value of entrust.abutment_phone
     *
     * @mbggenerated
     */
    public String getAbutmentPhone() {
        return abutmentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.abutment_phone
     *
     * @param abutmentPhone the value for entrust.abutment_phone
     *
     * @mbggenerated
     */
    public void setAbutmentPhone(String abutmentPhone) {
        this.abutmentPhone = abutmentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.case_frequency
     *
     * @return the value of entrust.case_frequency
     *
     * @mbggenerated
     */
    public String getCaseFrequency() {
        return caseFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.case_frequency
     *
     * @param caseFrequency the value for entrust.case_frequency
     *
     * @mbggenerated
     */
    public void setCaseFrequency(String caseFrequency) {
        this.caseFrequency = caseFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.effec_repay_period
     *
     * @return the value of entrust.effec_repay_period
     *
     * @mbggenerated
     */
    public String getEffecRepayPeriod() {
        return effecRepayPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.effec_repay_period
     *
     * @param effecRepayPeriod the value for entrust.effec_repay_period
     *
     * @mbggenerated
     */
    public void setEffecRepayPeriod(String effecRepayPeriod) {
        this.effecRepayPeriod = effecRepayPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.collec_nominal
     *
     * @return the value of entrust.collec_nominal
     *
     * @mbggenerated
     */
    public String getCollecNominal() {
        return collecNominal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.collec_nominal
     *
     * @param collecNominal the value for entrust.collec_nominal
     *
     * @mbggenerated
     */
    public void setCollecNominal(String collecNominal) {
        this.collecNominal = collecNominal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.collec_term
     *
     * @return the value of entrust.collec_term
     *
     * @mbggenerated
     */
    public String getCollecTerm() {
        return collecTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.collec_term
     *
     * @param collecTerm the value for entrust.collec_term
     *
     * @mbggenerated
     */
    public void setCollecTerm(String collecTerm) {
        this.collecTerm = collecTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.stay_require
     *
     * @return the value of entrust.stay_require
     *
     * @mbggenerated
     */
    public String getStayRequire() {
        return stayRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.stay_require
     *
     * @param stayRequire the value for entrust.stay_require
     *
     * @mbggenerated
     */
    public void setStayRequire(String stayRequire) {
        this.stayRequire = stayRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.back_require
     *
     * @return the value of entrust.back_require
     *
     * @mbggenerated
     */
    public String getBackRequire() {
        return backRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.back_require
     *
     * @param backRequire the value for entrust.back_require
     *
     * @mbggenerated
     */
    public void setBackRequire(String backRequire) {
        this.backRequire = backRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.report_period
     *
     * @return the value of entrust.report_period
     *
     * @mbggenerated
     */
    public String getReportPeriod() {
        return reportPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.report_period
     *
     * @param reportPeriod the value for entrust.report_period
     *
     * @mbggenerated
     */
    public void setReportPeriod(String reportPeriod) {
        this.reportPeriod = reportPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.settlement_period
     *
     * @return the value of entrust.settlement_period
     *
     * @mbggenerated
     */
    public String getSettlementPeriod() {
        return settlementPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.settlement_period
     *
     * @param settlementPeriod the value for entrust.settlement_period
     *
     * @mbggenerated
     */
    public void setSettlementPeriod(String settlementPeriod) {
        this.settlementPeriod = settlementPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.repayment_method
     *
     * @return the value of entrust.repayment_method
     *
     * @mbggenerated
     */
    public String getRepaymentMethod() {
        return repaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.repayment_method
     *
     * @param repaymentMethod the value for entrust.repayment_method
     *
     * @mbggenerated
     */
    public void setRepaymentMethod(String repaymentMethod) {
        this.repaymentMethod = repaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.discount_reduction
     *
     * @return the value of entrust.discount_reduction
     *
     * @mbggenerated
     */
    public String getDiscountReduction() {
        return discountReduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.discount_reduction
     *
     * @param discountReduction the value for entrust.discount_reduction
     *
     * @mbggenerated
     */
    public void setDiscountReduction(String discountReduction) {
        this.discountReduction = discountReduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.period_repayment_require
     *
     * @return the value of entrust.period_repayment_require
     *
     * @mbggenerated
     */
    public String getPeriodRepaymentRequire() {
        return periodRepaymentRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.period_repayment_require
     *
     * @param periodRepaymentRequire the value for entrust.period_repayment_require
     *
     * @mbggenerated
     */
    public void setPeriodRepaymentRequire(String periodRepaymentRequire) {
        this.periodRepaymentRequire = periodRepaymentRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.cancel_account
     *
     * @return the value of entrust.cancel_account
     *
     * @mbggenerated
     */
    public String getCancelAccount() {
        return cancelAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.cancel_account
     *
     * @param cancelAccount the value for entrust.cancel_account
     *
     * @mbggenerated
     */
    public void setCancelAccount(String cancelAccount) {
        this.cancelAccount = cancelAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.resource_retrieve_require
     *
     * @return the value of entrust.resource_retrieve_require
     *
     * @mbggenerated
     */
    public String getResourceRetrieveRequire() {
        return resourceRetrieveRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.resource_retrieve_require
     *
     * @param resourceRetrieveRequire the value for entrust.resource_retrieve_require
     *
     * @mbggenerated
     */
    public void setResourceRetrieveRequire(String resourceRetrieveRequire) {
        this.resourceRetrieveRequire = resourceRetrieveRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.collec_submit_require
     *
     * @return the value of entrust.collec_submit_require
     *
     * @mbggenerated
     */
    public String getCollecSubmitRequire() {
        return collecSubmitRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.collec_submit_require
     *
     * @param collecSubmitRequire the value for entrust.collec_submit_require
     *
     * @mbggenerated
     */
    public void setCollecSubmitRequire(String collecSubmitRequire) {
        this.collecSubmitRequire = collecSubmitRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.complaint_handle_require
     *
     * @return the value of entrust.complaint_handle_require
     *
     * @mbggenerated
     */
    public String getComplaintHandleRequire() {
        return complaintHandleRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.complaint_handle_require
     *
     * @param complaintHandleRequire the value for entrust.complaint_handle_require
     *
     * @mbggenerated
     */
    public void setComplaintHandleRequire(String complaintHandleRequire) {
        this.complaintHandleRequire = complaintHandleRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.tape_submit_require
     *
     * @return the value of entrust.tape_submit_require
     *
     * @mbggenerated
     */
    public String getTapeSubmitRequire() {
        return tapeSubmitRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.tape_submit_require
     *
     * @param tapeSubmitRequire the value for entrust.tape_submit_require
     *
     * @mbggenerated
     */
    public void setTapeSubmitRequire(String tapeSubmitRequire) {
        this.tapeSubmitRequire = tapeSubmitRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.data_destruc_require
     *
     * @return the value of entrust.data_destruc_require
     *
     * @mbggenerated
     */
    public String getDataDestrucRequire() {
        return dataDestrucRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.data_destruc_require
     *
     * @param dataDestrucRequire the value for entrust.data_destruc_require
     *
     * @mbggenerated
     */
    public void setDataDestrucRequire(String dataDestrucRequire) {
        this.dataDestrucRequire = dataDestrucRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.letter_recovery_require
     *
     * @return the value of entrust.letter_recovery_require
     *
     * @mbggenerated
     */
    public String getLetterRecoveryRequire() {
        return letterRecoveryRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.letter_recovery_require
     *
     * @param letterRecoveryRequire the value for entrust.letter_recovery_require
     *
     * @mbggenerated
     */
    public void setLetterRecoveryRequire(String letterRecoveryRequire) {
        this.letterRecoveryRequire = letterRecoveryRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.report_require
     *
     * @return the value of entrust.report_require
     *
     * @mbggenerated
     */
    public String getReportRequire() {
        return reportRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.report_require
     *
     * @param reportRequire the value for entrust.report_require
     *
     * @mbggenerated
     */
    public void setReportRequire(String reportRequire) {
        this.reportRequire = reportRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.cus_special_instruc
     *
     * @return the value of entrust.cus_special_instruc
     *
     * @mbggenerated
     */
    public String getCusSpecialInstruc() {
        return cusSpecialInstruc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.cus_special_instruc
     *
     * @param cusSpecialInstruc the value for entrust.cus_special_instruc
     *
     * @mbggenerated
     */
    public void setCusSpecialInstruc(String cusSpecialInstruc) {
        this.cusSpecialInstruc = cusSpecialInstruc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.state
     *
     * @return the value of entrust.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.state
     *
     * @param state the value for entrust.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.modify_time
     *
     * @return the value of entrust.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.modify_time
     *
     * @param modifyTime the value for entrust.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.contract_name
     *
     * @return the value of entrust.contract_name
     *
     * @mbggenerated
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.contract_name
     *
     * @param contractName the value for entrust.contract_name
     *
     * @mbggenerated
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.create_emp_id
     *
     * @return the value of entrust.create_emp_id
     *
     * @mbggenerated
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.create_emp_id
     *
     * @param createEmpId the value for entrust.create_emp_id
     *
     * @mbggenerated
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.create_emp_name
     *
     * @return the value of entrust.create_emp_name
     *
     * @mbggenerated
     */
    public String getCreateEmpName() {
        return createEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.create_emp_name
     *
     * @param createEmpName the value for entrust.create_emp_name
     *
     * @mbggenerated
     */
    public void setCreateEmpName(String createEmpName) {
        this.createEmpName = createEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust.create_time
     *
     * @return the value of entrust.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust.create_time
     *
     * @param createTime the value for entrust.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Entrust other = (Entrust) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getCooperateDate() == null ? other.getCooperateDate() == null : this.getCooperateDate().equals(other.getCooperateDate()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getServiceHotline() == null ? other.getServiceHotline() == null : this.getServiceHotline().equals(other.getServiceHotline()))
            && (this.getAbutmentPerson() == null ? other.getAbutmentPerson() == null : this.getAbutmentPerson().equals(other.getAbutmentPerson()))
            && (this.getAbutmentEmail() == null ? other.getAbutmentEmail() == null : this.getAbutmentEmail().equals(other.getAbutmentEmail()))
            && (this.getAbutmentPhone() == null ? other.getAbutmentPhone() == null : this.getAbutmentPhone().equals(other.getAbutmentPhone()))
            && (this.getCaseFrequency() == null ? other.getCaseFrequency() == null : this.getCaseFrequency().equals(other.getCaseFrequency()))
            && (this.getEffecRepayPeriod() == null ? other.getEffecRepayPeriod() == null : this.getEffecRepayPeriod().equals(other.getEffecRepayPeriod()))
            && (this.getCollecNominal() == null ? other.getCollecNominal() == null : this.getCollecNominal().equals(other.getCollecNominal()))
            && (this.getCollecTerm() == null ? other.getCollecTerm() == null : this.getCollecTerm().equals(other.getCollecTerm()))
            && (this.getStayRequire() == null ? other.getStayRequire() == null : this.getStayRequire().equals(other.getStayRequire()))
            && (this.getBackRequire() == null ? other.getBackRequire() == null : this.getBackRequire().equals(other.getBackRequire()))
            && (this.getReportPeriod() == null ? other.getReportPeriod() == null : this.getReportPeriod().equals(other.getReportPeriod()))
            && (this.getSettlementPeriod() == null ? other.getSettlementPeriod() == null : this.getSettlementPeriod().equals(other.getSettlementPeriod()))
            && (this.getRepaymentMethod() == null ? other.getRepaymentMethod() == null : this.getRepaymentMethod().equals(other.getRepaymentMethod()))
            && (this.getDiscountReduction() == null ? other.getDiscountReduction() == null : this.getDiscountReduction().equals(other.getDiscountReduction()))
            && (this.getPeriodRepaymentRequire() == null ? other.getPeriodRepaymentRequire() == null : this.getPeriodRepaymentRequire().equals(other.getPeriodRepaymentRequire()))
            && (this.getCancelAccount() == null ? other.getCancelAccount() == null : this.getCancelAccount().equals(other.getCancelAccount()))
            && (this.getResourceRetrieveRequire() == null ? other.getResourceRetrieveRequire() == null : this.getResourceRetrieveRequire().equals(other.getResourceRetrieveRequire()))
            && (this.getCollecSubmitRequire() == null ? other.getCollecSubmitRequire() == null : this.getCollecSubmitRequire().equals(other.getCollecSubmitRequire()))
            && (this.getComplaintHandleRequire() == null ? other.getComplaintHandleRequire() == null : this.getComplaintHandleRequire().equals(other.getComplaintHandleRequire()))
            && (this.getTapeSubmitRequire() == null ? other.getTapeSubmitRequire() == null : this.getTapeSubmitRequire().equals(other.getTapeSubmitRequire()))
            && (this.getDataDestrucRequire() == null ? other.getDataDestrucRequire() == null : this.getDataDestrucRequire().equals(other.getDataDestrucRequire()))
            && (this.getLetterRecoveryRequire() == null ? other.getLetterRecoveryRequire() == null : this.getLetterRecoveryRequire().equals(other.getLetterRecoveryRequire()))
            && (this.getReportRequire() == null ? other.getReportRequire() == null : this.getReportRequire().equals(other.getReportRequire()))
            && (this.getCusSpecialInstruc() == null ? other.getCusSpecialInstruc() == null : this.getCusSpecialInstruc().equals(other.getCusSpecialInstruc()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getContractName() == null ? other.getContractName() == null : this.getContractName().equals(other.getContractName()))
            && (this.getCreateEmpId() == null ? other.getCreateEmpId() == null : this.getCreateEmpId().equals(other.getCreateEmpId()))
            && (this.getCreateEmpName() == null ? other.getCreateEmpName() == null : this.getCreateEmpName().equals(other.getCreateEmpName()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCooperateDate() == null) ? 0 : getCooperateDate().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getServiceHotline() == null) ? 0 : getServiceHotline().hashCode());
        result = prime * result + ((getAbutmentPerson() == null) ? 0 : getAbutmentPerson().hashCode());
        result = prime * result + ((getAbutmentEmail() == null) ? 0 : getAbutmentEmail().hashCode());
        result = prime * result + ((getAbutmentPhone() == null) ? 0 : getAbutmentPhone().hashCode());
        result = prime * result + ((getCaseFrequency() == null) ? 0 : getCaseFrequency().hashCode());
        result = prime * result + ((getEffecRepayPeriod() == null) ? 0 : getEffecRepayPeriod().hashCode());
        result = prime * result + ((getCollecNominal() == null) ? 0 : getCollecNominal().hashCode());
        result = prime * result + ((getCollecTerm() == null) ? 0 : getCollecTerm().hashCode());
        result = prime * result + ((getStayRequire() == null) ? 0 : getStayRequire().hashCode());
        result = prime * result + ((getBackRequire() == null) ? 0 : getBackRequire().hashCode());
        result = prime * result + ((getReportPeriod() == null) ? 0 : getReportPeriod().hashCode());
        result = prime * result + ((getSettlementPeriod() == null) ? 0 : getSettlementPeriod().hashCode());
        result = prime * result + ((getRepaymentMethod() == null) ? 0 : getRepaymentMethod().hashCode());
        result = prime * result + ((getDiscountReduction() == null) ? 0 : getDiscountReduction().hashCode());
        result = prime * result + ((getPeriodRepaymentRequire() == null) ? 0 : getPeriodRepaymentRequire().hashCode());
        result = prime * result + ((getCancelAccount() == null) ? 0 : getCancelAccount().hashCode());
        result = prime * result + ((getResourceRetrieveRequire() == null) ? 0 : getResourceRetrieveRequire().hashCode());
        result = prime * result + ((getCollecSubmitRequire() == null) ? 0 : getCollecSubmitRequire().hashCode());
        result = prime * result + ((getComplaintHandleRequire() == null) ? 0 : getComplaintHandleRequire().hashCode());
        result = prime * result + ((getTapeSubmitRequire() == null) ? 0 : getTapeSubmitRequire().hashCode());
        result = prime * result + ((getDataDestrucRequire() == null) ? 0 : getDataDestrucRequire().hashCode());
        result = prime * result + ((getLetterRecoveryRequire() == null) ? 0 : getLetterRecoveryRequire().hashCode());
        result = prime * result + ((getReportRequire() == null) ? 0 : getReportRequire().hashCode());
        result = prime * result + ((getCusSpecialInstruc() == null) ? 0 : getCusSpecialInstruc().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getContractName() == null) ? 0 : getContractName().hashCode());
        result = prime * result + ((getCreateEmpId() == null) ? 0 : getCreateEmpId().hashCode());
        result = prime * result + ((getCreateEmpName() == null) ? 0 : getCreateEmpName().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", cooperateDate=").append(cooperateDate);
        sb.append(", address=").append(address);
        sb.append(", serviceHotline=").append(serviceHotline);
        sb.append(", abutmentPerson=").append(abutmentPerson);
        sb.append(", abutmentEmail=").append(abutmentEmail);
        sb.append(", abutmentPhone=").append(abutmentPhone);
        sb.append(", caseFrequency=").append(caseFrequency);
        sb.append(", effecRepayPeriod=").append(effecRepayPeriod);
        sb.append(", collecNominal=").append(collecNominal);
        sb.append(", collecTerm=").append(collecTerm);
        sb.append(", stayRequire=").append(stayRequire);
        sb.append(", backRequire=").append(backRequire);
        sb.append(", reportPeriod=").append(reportPeriod);
        sb.append(", settlementPeriod=").append(settlementPeriod);
        sb.append(", repaymentMethod=").append(repaymentMethod);
        sb.append(", discountReduction=").append(discountReduction);
        sb.append(", periodRepaymentRequire=").append(periodRepaymentRequire);
        sb.append(", cancelAccount=").append(cancelAccount);
        sb.append(", resourceRetrieveRequire=").append(resourceRetrieveRequire);
        sb.append(", collecSubmitRequire=").append(collecSubmitRequire);
        sb.append(", complaintHandleRequire=").append(complaintHandleRequire);
        sb.append(", tapeSubmitRequire=").append(tapeSubmitRequire);
        sb.append(", dataDestrucRequire=").append(dataDestrucRequire);
        sb.append(", letterRecoveryRequire=").append(letterRecoveryRequire);
        sb.append(", reportRequire=").append(reportRequire);
        sb.append(", cusSpecialInstruc=").append(cusSpecialInstruc);
        sb.append(", state=").append(state);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", contractName=").append(contractName);
        sb.append(", createEmpId=").append(createEmpId);
        sb.append(", createEmpName=").append(createEmpName);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}